# This file is used to test production compose deployment locally. It contains
# some overrides that allow the services to run in a local environment.

services:
  frontend-astro:
    build:
      # Use host network mode to allow access to Directus hosted on
      # `http://localhost` during build.
      network: host
    ports:
      - 8081:80
